import path from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "./utils.mjs";

export const SECTION_TITLES = {
  product: "产品与功能更新",
  research: "前沿研究",
  opensource: "开源TOP项目",
  industry: "行业展望与社会影响",
  social: "社媒分享",
};

const RSSHUB_BASE = process.env.CONTENT_AGENT_RSSHUB_BASE || "https://rsshub.app";

export const DEFAULT_CONFIG = {
  brand: "焦糖星球",
  cacheDir: ".cache/content-agent",
  output: {
    dailiesDir: "src/content/dailies",
    weeklyDir: "src/content/posts/weekly",
  },
  media: {
    localize: true,
    publicDir: "public",
    outputDir: "generated/content-agent",
    maxImagesPerItem: 1,
    maxVideosPerItem: 1,
    maxImageBytes: 12 * 1024 * 1024,
    maxVideoBytes: 48 * 1024 * 1024,
    timeoutMs: 15_000,
  },
  ai: {
    provider: process.env.CONTENT_AGENT_AI_PROVIDER || "openai",
    model: process.env.CONTENT_AGENT_MODEL || "gpt-5.4",
    baseUrl: process.env.CONTENT_AGENT_OPENAI_BASE_URL || "https://api.openai.com/v1",
    apiKey: process.env.OPENAI_API_KEY || process.env.CONTENT_AGENT_OPENAI_API_KEY || "",
    reasoningEffort: process.env.CONTENT_AGENT_REASONING_EFFORT || "low",
  },
  scoring: {
    sourceWeights: {
      official: 18,
      github: 15,
      paper: 14,
      news: 13,
      social: 11,
      rss: 10,
      search: 9,
      folo: 8,
    },
    coreSelection: {
      maxPerSourceId: 8,
      maxAgeHours: 168,
      sourceTypeCaps: {
        official: 10,
        news: 36,
        github: 18,
        paper: 10,
        social: 24,
        rss: 24,
        search: 8,
        folo: 8,
      },
      sourceIdCaps: {
        "openai-news": 5,
        "google-ai-blog": 4,
        "google-research-blog": 4,
        "microsoft-ai": 4,
        "nvidia-ai": 4,
        "aibase-news": 10,
        "qbitai-feed": 8,
        "ithome-rss": 5,
        "infoq-cn": 5,
        "geekpark-rss": 5,
        "leiphone-rss": 5,
        "36kr-rss": 5,
        "oschina-news": 5,
        "github-trending": 8,
        "arxiv-ai": 5,
        "arxiv-cl": 4,
        "arxiv-lg": 4,
        "arxiv-cv": 4,
        "hn-ai-search": 8,
        "reddit-localllama": 4,
        "reddit-machinelearning": 4,
        "reddit-openai": 4,
        "reddit-artificial": 4,
        "x-official-ai-rsshub": 12,
        "x-ai-keyword-rsshub": 12,
        "wechat-ai-rsshub": 10,
        "github-ai-project-search": 10,
        "github-agent-org-search": 8,
        "github-curated-agent-repos": 8,
        "product-changelog-rss": 10,
        "ai-newsletter-rss": 8,
        "paper-trend-rss": 8,
        "video-ai-rsshub": 8,
      },
    },
  },
  sources: [
    {
      id: "openai-news",
      type: "rss",
      name: "OpenAI News",
      url: "https://openai.com/news/rss.xml",
      homepage: "https://openai.com/news/",
      sourceType: "official",
      section: "product",
      weight: 19,
      tags: ["官方"],
    },
    {
      id: "anthropic-news",
      type: "rss",
      name: "Anthropic News",
      url: "https://www.anthropic.com/news/rss.xml",
      homepage: "https://www.anthropic.com/news",
      sourceType: "official",
      section: "product",
      weight: 18,
      tags: ["官方"],
      enabled: process.env.CONTENT_AGENT_ANTHROPIC_RSS === "true",
    },
    {
      id: "google-ai-blog",
      type: "rss",
      name: "Google AI Blog",
      url: "https://blog.google/technology/ai/rss/",
      homepage: "https://blog.google/technology/ai/",
      sourceType: "official",
      section: "product",
      weight: 18,
      tags: ["官方", "Google"],
    },
    {
      id: "google-research-blog",
      type: "rss",
      name: "Google Research Blog",
      url: "https://research.google/blog/rss/",
      homepage: "https://research.google/blog/",
      sourceType: "official",
      section: "research",
      weight: 17,
      tags: ["官方", "研究"],
    },
    {
      id: "microsoft-ai",
      type: "rss",
      name: "Microsoft AI",
      url: "https://blogs.microsoft.com/ai/feed/",
      homepage: "https://blogs.microsoft.com/ai/",
      sourceType: "official",
      section: "product",
      weight: 17,
      tags: ["官方", "Microsoft"],
    },
    {
      id: "nvidia-ai",
      type: "rss",
      name: "NVIDIA AI Blog",
      url: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
      homepage: "https://blogs.nvidia.com/blog/category/deep-learning/",
      sourceType: "official",
      section: "industry",
      weight: 16,
      tags: ["官方", "NVIDIA", "算力"],
    },
    {
      id: "meta-research",
      type: "rss",
      name: "Meta Research",
      url: "https://research.facebook.com/feed/",
      homepage: "https://research.facebook.com/blog/",
      sourceType: "official",
      section: "research",
      weight: 15,
      tags: ["官方", "Meta", "研究"],
    },
    {
      id: "meta-engineering",
      type: "rss",
      name: "Engineering at Meta",
      url: "https://engineering.fb.com/feed/",
      homepage: "https://engineering.fb.com/",
      sourceType: "rss",
      section: "industry",
      weight: 14,
      tags: ["Meta", "工程"],
    },
    {
      id: "huggingface-blog",
      type: "rss",
      name: "Hugging Face Blog",
      url: "https://huggingface.co/blog/feed.xml",
      homepage: "https://huggingface.co/blog",
      sourceType: "rss",
      section: "research",
      weight: 14,
      tags: ["HuggingFace", "开源"],
    },
    {
      id: "github-changelog",
      type: "rss",
      name: "GitHub Changelog",
      url: "https://github.blog/changelog/feed/",
      homepage: "https://github.blog/changelog/",
      sourceType: "rss",
      section: "opensource",
      weight: 12,
      tags: ["GitHub", "开发者"],
    },
    {
      id: "arxiv-ai",
      type: "rss",
      name: "arXiv cs.AI",
      url: "https://rss.arxiv.org/rss/cs.AI",
      homepage: "https://arxiv.org/list/cs.AI/recent",
      sourceType: "paper",
      section: "research",
      weight: 14,
      tags: ["论文"],
    },
    {
      id: "arxiv-cl",
      type: "rss",
      name: "arXiv cs.CL",
      url: "https://rss.arxiv.org/rss/cs.CL",
      homepage: "https://arxiv.org/list/cs.CL/recent",
      sourceType: "paper",
      section: "research",
      weight: 13,
      tags: ["论文", "语言模型"],
    },
    {
      id: "arxiv-lg",
      type: "rss",
      name: "arXiv cs.LG",
      url: "https://rss.arxiv.org/rss/cs.LG",
      homepage: "https://arxiv.org/list/cs.LG/recent",
      sourceType: "paper",
      section: "research",
      weight: 13,
      tags: ["论文", "机器学习"],
    },
    {
      id: "arxiv-cv",
      type: "rss",
      name: "arXiv cs.CV",
      url: "https://rss.arxiv.org/rss/cs.CV",
      homepage: "https://arxiv.org/list/cs.CV/recent",
      sourceType: "paper",
      section: "research",
      weight: 12,
      tags: ["论文", "多模态"],
    },
    {
      id: "github-trending",
      type: "github-trending",
      name: "GitHub Trending",
      url: "https://github.com/trending?spoken_language_code=&since=daily",
      sourceType: "github",
      section: "opensource",
      weight: 16,
      tags: ["GitHub", "开源"],
    },
    {
      id: "aibase-news",
      type: "aibase-news",
      name: "AIbase",
      url: "https://www.aibase.com/zh/news",
      homepage: "https://www.aibase.com/zh/news",
      sourceType: "news",
      weight: 15,
      tags: ["中文媒体"],
    },
    {
      id: "qbitai-feed",
      type: "rss",
      name: "量子位",
      url: "https://www.qbitai.com/feed",
      homepage: "https://www.qbitai.com/",
      sourceType: "news",
      weight: 15,
      tags: ["中文媒体", "量子位"],
      enrichMedia: true,
      enrichMediaLimit: 10,
    },
    {
      id: "ithome-rss",
      type: "rss",
      name: "IT之家",
      url: "https://www.ithome.com/rss/",
      homepage: "https://www.ithome.com/",
      sourceType: "news",
      section: "industry",
      weight: 11,
      tags: ["中文媒体", "科技媒体"],
    },
    {
      id: "infoq-cn",
      type: "rss",
      name: "InfoQ 中文",
      url: "https://www.infoq.cn/feed",
      homepage: "https://www.infoq.cn/",
      sourceType: "news",
      section: "industry",
      weight: 12,
      tags: ["中文媒体", "开发者"],
    },
    {
      id: "geekpark-rss",
      type: "rss",
      name: "极客公园",
      url: "https://www.geekpark.net/rss",
      homepage: "https://www.geekpark.net/",
      sourceType: "news",
      section: "industry",
      weight: 12,
      tags: ["中文媒体", "产品"],
    },
    {
      id: "leiphone-rss",
      type: "rss",
      name: "雷峰网",
      url: "https://www.leiphone.com/feed",
      homepage: "https://www.leiphone.com/",
      sourceType: "news",
      section: "industry",
      weight: 12,
      tags: ["中文媒体", "产业"],
    },
    {
      id: "36kr-rss",
      type: "rss",
      name: "36氪",
      url: "https://36kr.com/feed",
      homepage: "https://36kr.com/",
      sourceType: "news",
      section: "industry",
      weight: 11,
      tags: ["中文媒体", "商业化"],
    },
    {
      id: "oschina-news",
      type: "rss",
      name: "OSCHINA",
      url: "https://www.oschina.net/news/rss",
      homepage: "https://www.oschina.net/news",
      sourceType: "news",
      section: "opensource",
      weight: 11,
      tags: ["中文媒体", "开源"],
    },
    {
      id: "techcrunch-ai",
      type: "rss",
      name: "TechCrunch AI",
      url: "https://techcrunch.com/category/artificial-intelligence/feed/",
      homepage: "https://techcrunch.com/category/artificial-intelligence/",
      sourceType: "news",
      section: "industry",
      weight: 14,
      tags: ["英文媒体", "商业化"],
    },
    {
      id: "venturebeat-ai",
      type: "rss",
      name: "VentureBeat AI",
      url: "https://venturebeat.com/category/ai/feed/",
      homepage: "https://venturebeat.com/category/ai/",
      sourceType: "news",
      section: "industry",
      weight: 14,
      tags: ["英文媒体", "商业化"],
    },
    {
      id: "the-decoder",
      type: "rss",
      name: "The Decoder",
      url: "https://the-decoder.com/feed/",
      homepage: "https://the-decoder.com/",
      sourceType: "news",
      weight: 13,
      tags: ["英文媒体"],
    },
    {
      id: "ars-ai",
      type: "rss",
      name: "Ars Technica AI",
      url: "https://arstechnica.com/ai/feed/",
      homepage: "https://arstechnica.com/ai/",
      sourceType: "news",
      section: "industry",
      weight: 13,
      tags: ["英文媒体", "技术"],
    },
    {
      id: "mit-tr-ai",
      type: "rss",
      name: "MIT Technology Review AI",
      url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
      homepage: "https://www.technologyreview.com/topic/artificial-intelligence/",
      sourceType: "news",
      section: "industry",
      weight: 13,
      tags: ["英文媒体", "趋势"],
    },
    {
      id: "the-gradient",
      type: "rss",
      name: "The Gradient",
      url: "https://thegradient.pub/rss/",
      homepage: "https://thegradient.pub/",
      sourceType: "rss",
      section: "research",
      weight: 12,
      tags: ["研究", "长文"],
    },
    {
      id: "latent-space",
      type: "rss",
      name: "Latent Space",
      url: "https://www.latent.space/feed",
      homepage: "https://www.latent.space/",
      sourceType: "rss",
      section: "industry",
      weight: 13,
      tags: ["播客", "开发者"],
    },
    {
      id: "simon-willison",
      type: "rss",
      name: "Simon Willison",
      url: "https://simonwillison.net/atom/everything/",
      homepage: "https://simonwillison.net/",
      sourceType: "social",
      section: "social",
      weight: 13,
      tags: ["开发者社区"],
    },
    {
      id: "import-ai",
      type: "rss",
      name: "Import AI",
      url: "https://jack-clark.net/feed/",
      homepage: "https://jack-clark.net/",
      sourceType: "rss",
      section: "research",
      weight: 12,
      tags: ["研究", "政策"],
    },
    {
      id: "newshacker-rss",
      type: "rss",
      name: "News Hacker",
      url: "https://api.newshacker.me/rss",
      homepage: "https://newshacker.me",
      sourceType: "social",
      section: "social",
      weight: 12,
      tags: ["开发者社区"],
    },
    {
      id: "hn-ai-search",
      type: "hacker-news-search",
      name: "Hacker News AI Search",
      sourceType: "social",
      section: "social",
      queries: ["AI agent", "LLM", "OpenAI", "Claude", "Gemini", "AI coding", "MCP"],
      hours: 72,
      limit: 12,
      weight: 14,
      tags: ["HN", "开发者社区"],
    },
    {
      id: "reddit-localllama",
      type: "rss",
      name: "Reddit LocalLLaMA",
      url: "https://www.reddit.com/r/LocalLLaMA/top/.rss?t=day",
      homepage: "https://www.reddit.com/r/LocalLLaMA/",
      sourceType: "social",
      section: "social",
      weight: 12,
      tags: ["Reddit", "开源模型"],
    },
    {
      id: "reddit-machinelearning",
      type: "rss",
      name: "Reddit MachineLearning",
      url: "https://www.reddit.com/r/MachineLearning/hot/.rss",
      homepage: "https://www.reddit.com/r/MachineLearning/",
      sourceType: "social",
      section: "research",
      weight: 11,
      tags: ["Reddit", "研究"],
    },
    {
      id: "reddit-openai",
      type: "rss",
      name: "Reddit OpenAI",
      url: "https://www.reddit.com/r/OpenAI/hot/.rss",
      homepage: "https://www.reddit.com/r/OpenAI/",
      sourceType: "social",
      section: "social",
      weight: 11,
      tags: ["Reddit", "OpenAI"],
    },
    {
      id: "reddit-artificial",
      type: "rss",
      name: "Reddit Artificial",
      url: "https://www.reddit.com/r/artificial/hot/.rss",
      homepage: "https://www.reddit.com/r/artificial/",
      sourceType: "social",
      section: "social",
      weight: 10,
      tags: ["Reddit", "AI社区"],
    },
    {
      id: "x-official-ai-rsshub",
      type: "rsshub",
      name: "X Official AI Accounts",
      baseUrl: RSSHUB_BASE,
      sourceType: "social",
      section: "social",
      weight: 15,
      routeTimeoutMs: 8_000,
      tags: ["X", "社媒", "官方"],
      enrichMedia: true,
      routes: [
        { path: "/twitter/user/OpenAI", name: "OpenAI on X", section: "product", tags: ["OpenAI"] },
        { path: "/twitter/user/AnthropicAI", name: "Anthropic on X", section: "product", tags: ["Anthropic"] },
        { path: "/twitter/user/GoogleDeepMind", name: "Google DeepMind on X", section: "research", tags: ["Google"] },
        { path: "/twitter/user/xai", name: "xAI on X", section: "industry", tags: ["xAI"] },
        { path: "/twitter/user/perplexity_ai", name: "Perplexity on X", section: "product", tags: ["Perplexity"] },
        { path: "/twitter/user/github", name: "GitHub on X", section: "opensource", tags: ["GitHub"] },
        { path: "/twitter/user/vercel", name: "Vercel on X", section: "opensource", tags: ["Vercel"] },
        { path: "/twitter/user/warpdotdev", name: "Warp on X", section: "opensource", tags: ["Warp"] },
        { path: "/twitter/user/cursor_ai", name: "Cursor on X", section: "product", tags: ["Cursor", "AI编程"] },
        { path: "/twitter/user/trae_ai", name: "Trae on X", section: "product", tags: ["Trae", "AI编程"] },
        { path: "/twitter/user/a16z", name: "a16z on X", section: "industry", tags: ["a16z", "投资"] },
        { path: "/twitter/user/karpathy", name: "Karpathy on X", section: "social", tags: ["开发者社区"] },
        { path: "/twitter/user/SpaceX", name: "SpaceX on X", section: "industry", tags: ["SpaceX", "算力"] },
      ],
    },
    {
      id: "x-ai-keyword-rsshub",
      type: "rsshub",
      name: "X AI Keyword Radar",
      baseUrl: RSSHUB_BASE,
      sourceType: "social",
      section: "social",
      weight: 14,
      routeTimeoutMs: 8_000,
      tags: ["X", "社媒", "爆点"],
      enrichMedia: true,
      routes: [
        { path: `/twitter/search/${encodeURIComponent("Codex OR Claude Code OR AI agent")}`, name: "X Search: Coding Agents", tags: ["AI编程"] },
        { path: `/twitter/search/${encodeURIComponent("MCP OR AI automation OR agent workflow")}`, name: "X Search: Agent Workflow", tags: ["Agent"] },
        { path: `/twitter/search/${encodeURIComponent("Perplexity Mac OR Trae mobile OR Cursor")}`, name: "X Search: AI Products", tags: ["产品"] },
        { path: `/twitter/search/${encodeURIComponent("GEO prompts OR generative engine optimization")}`, name: "X Search: GEO Prompts", tags: ["AI营销"] },
        { path: `/twitter/search/${encodeURIComponent("GPT-5 visual OR realtime voice model OR OpenAI CLI")}`, name: "X Search: OpenAI Launches", tags: ["OpenAI"] },
        { path: `/twitter/search/${encodeURIComponent("Trae mobile OR Trae iOS OR Trae Android")}`, name: "X Search: Trae Mobile", tags: ["Trae", "AI编程"] },
        { path: `/twitter/search/${encodeURIComponent("Warp Skills OR Warp AI terminal")}`, name: "X Search: Warp Skills", tags: ["Warp", "AI编程"] },
        { path: `/twitter/search/${encodeURIComponent("GPT-5 visual OR computer-use visual protocol OR visual protocol agents")}`, name: "X Search: GPT-5 Visual Protocol", tags: ["视觉", "Agent"] },
        { path: `/twitter/search/${encodeURIComponent("GEO prompts OR generative engine optimization OR AI search optimization")}`, name: "X Search: AI Search Marketing", tags: ["AI营销"] },
        { path: `/twitter/search/${encodeURIComponent("AI bubble OR a16z AI unemployment OR AI unemployment")}`, name: "X Search: AI Labor and Bubble", tags: ["a16z", "产业"] },
        { path: `/twitter/search/${encodeURIComponent("xAI SpaceX Colossus OR SpaceX compute OR Claude Code SpaceX")}`, name: "X Search: xAI SpaceX Compute", tags: ["xAI", "算力"] },
        { path: `/twitter/search/${encodeURIComponent("OpenSearch-VL OR MSM alignment OR model organism alignment")}`, name: "X Search: Research Propagation", tags: ["研究", "可解释性"] },
      ],
    },
    {
      id: "wechat-ai-rsshub",
      type: "rsshub",
      name: "WeChat AI Accounts",
      baseUrl: RSSHUB_BASE,
      sourceType: "news",
      section: "industry",
      weight: 14,
      routeTimeoutMs: 8_000,
      tags: ["微信公众号", "中文私域"],
      enrichMedia: true,
      routes: [
        ...routesFromEnv("CONTENT_AGENT_WECHAT_RSSHUB_ROUTES"),
        { path: "/wechat/mp/jiqizhixin", name: "机器之心公众号", tags: ["机器之心"] },
        { path: "/wechat/mp/xinzhiyuan", name: "新智元公众号", tags: ["新智元"] },
        { path: "/wechat/mp/qbitai", name: "量子位公众号", tags: ["量子位"] },
        { path: "/wechat/mp/aitechtalk", name: "AI科技评论公众号", tags: ["AI科技评论"] },
      ],
    },
    {
      id: "github-ai-project-search",
      type: "github-search",
      name: "GitHub AI Project Search",
      sourceType: "github",
      section: "opensource",
      weight: 16,
      limit: 10,
      pushedWithinDays: 14,
      tags: ["GitHub", "开源", "增量发现"],
      queries: [
        "AI agent stars:>300",
        "MCP agent stars:>100",
        "AI coding agent stars:>100",
        "RAG agent stars:>300",
        "LLM inference stars:>300",
        "GEO prompt stars:>20",
        "computer use agent stars:>50",
        "generative engine optimization prompts stars:>20",
        "agent template vercel ai stars:>50",
        "visual protocol computer use agent stars:>20",
        "OpenSearch-VL agent",
      ],
    },
    {
      id: "github-agent-org-search",
      type: "github-search",
      name: "GitHub Agent Org Search",
      sourceType: "github",
      section: "opensource",
      weight: 15,
      limit: 8,
      pushedWithinDays: 30,
      tags: ["GitHub", "组织监听"],
      queries: [
        "org:vercel ai agent",
        "org:anthropics claude agent",
        "org:openai codex OR agent",
        "org:bytedance agent OR llm",
        "org:microsoft copilot agent",
        "org:github copilot agent",
      ],
    },
    {
      id: "github-curated-agent-repos",
      type: "github-repos",
      name: "GitHub Curated Agent Repos",
      sourceType: "github",
      section: "opensource",
      weight: 18,
      tags: ["GitHub", "精选开源"],
      repos: [
        { repo: "block/goose", tags: ["Agent", "AI编程"] },
        { repo: "bytedance/deer-flow", tags: ["Deep Research", "Agent"] },
        { repo: "VectifyAI/PageIndex", tags: ["RAG", "文档索引"] },
        { repo: "z-lab/dflash", tags: ["推理加速"] },
        { repo: "vercel/ai", tags: ["Vercel", "AI SDK", "Agent"] },
        { repo: "vercel/ai-chatbot", tags: ["Vercel", "AI应用"] },
        { repo: "anthropics/claude-agent-sdk-python", tags: ["Anthropic", "SDK"] },
        { repo: "anthropics/claude-agent-sdk-typescript", tags: ["Anthropic", "SDK"] },
      ],
    },
    {
      id: "product-changelog-rss",
      type: "rsshub",
      name: "Product Changelog Bundle",
      sourceType: "rss",
      section: "product",
      weight: 14,
      routeTimeoutMs: 8_000,
      tags: ["产品更新", "Changelog"],
      routes: [
        { url: "https://github.blog/changelog/feed/", name: "GitHub Changelog", tags: ["GitHub"] },
        { url: "https://vercel.com/changelog/rss", name: "Vercel Changelog", tags: ["Vercel"] },
        { url: "https://huggingface.co/blog/feed.xml", name: "Hugging Face Blog", tags: ["HuggingFace"] },
        { url: "https://simonwillison.net/atom/everything/", name: "Simon Willison", tags: ["开发者社区"] },
      ],
    },
    {
      id: "ai-newsletter-rss",
      type: "rsshub",
      name: "AI Newsletter Bundle",
      sourceType: "rss",
      section: "industry",
      weight: 13,
      routeTimeoutMs: 8_000,
      tags: ["英文简报", "趋势"],
      routes: [
        { url: "https://www.latent.space/feed", name: "Latent Space", tags: ["开发者"] },
        { url: "https://jack-clark.net/feed/", name: "Import AI", tags: ["研究", "政策"] },
        { url: "https://www.therundown.ai/feed", name: "The Rundown AI", tags: ["AI简报"] },
        { url: "https://bensbites.com/feed", name: "Ben's Bites", tags: ["AI简报"] },
      ],
    },
    {
      id: "paper-trend-rss",
      type: "rsshub",
      name: "Paper Trend Bundle",
      sourceType: "paper",
      section: "research",
      weight: 14,
      routeTimeoutMs: 8_000,
      tags: ["论文热度", "研究"],
      routes: [
        { url: "https://huggingface.co/papers/rss", name: "Hugging Face Daily Papers", tags: ["HuggingFace"] },
        { url: "https://paperswithcode.com/rss", name: "Papers with Code", tags: ["PapersWithCode"] },
        { url: "https://thegradient.pub/rss/", name: "The Gradient", tags: ["长文"] },
      ],
    },
    {
      id: "video-ai-rsshub",
      type: "rsshub",
      name: "AI Video Radar",
      baseUrl: RSSHUB_BASE,
      sourceType: "social",
      section: "social",
      weight: 12,
      routeTimeoutMs: 8_000,
      tags: ["视频", "演示"],
      enrichMedia: true,
      routes: [
        ...routesFromEnv("CONTENT_AGENT_VIDEO_RSSHUB_ROUTES"),
        { path: `/youtube/keyword/${encodeURIComponent("AI agent demo")}`, name: "YouTube AI Agent Demo", tags: ["YouTube"] },
        { path: `/youtube/keyword/${encodeURIComponent("Claude Code Codex Cursor")}`, name: "YouTube AI Coding", tags: ["YouTube", "AI编程"] },
        { path: `/bilibili/search/${encodeURIComponent("AI 智能体")}`, name: "Bilibili AI Agent", tags: ["B站"] },
      ],
    },
    {
      id: "ai-search",
      type: "ai-search",
      name: "AI Search",
      keyword: "AI 行业最新动态 Agent 模型 开源 项目 论文",
      sourceType: "search",
      section: "industry",
      weight: 12,
      tags: ["AI检索"],
      enabled: process.env.CONTENT_AGENT_AI_SEARCH === "true",
    },
    {
      id: "folo-ai",
      type: "folo",
      name: "Folo AI Lists",
      apiUrl: process.env.FOLO_DATA_API || "https://api.follow.is/entries",
      listIds: (process.env.FOLO_LIST_IDS || "").split(",").map((item) => item.trim()).filter(Boolean),
      cookie: process.env.FOLO_COOKIE || "",
      sourceType: "folo",
      section: "social",
      weight: 13,
      tags: ["Folo"],
      enabled: Boolean(process.env.FOLO_COOKIE && process.env.FOLO_LIST_IDS),
    },
  ],
};

export async function loadConfig({ projectRoot = process.cwd(), cliArgs = parseArgs() } = {}) {
  const configPath = path.join(projectRoot, "content-agent.config.mjs");
  let userConfig = {};
  try {
    userConfig = (await import(pathToFileURL(configPath).href)).default ?? {};
  } catch (error) {
    if (error?.code !== "ERR_MODULE_NOT_FOUND" && error?.code !== "ENOENT") throw error;
  }

  const merged = mergeConfig(DEFAULT_CONFIG, userConfig);
  if (cliArgs.brand) merged.brand = cliArgs.brand;
  if (cliArgs.cacheDir) merged.cacheDir = cliArgs.cacheDir;
  if (cliArgs.model) merged.ai.model = cliArgs.model;
  if (cliArgs.provider) merged.ai.provider = cliArgs.provider;
  return merged;
}

function mergeConfig(base, override) {
  const out = structuredClone(base);
  for (const [key, value] of Object.entries(override ?? {})) {
    if (Array.isArray(value)) {
      out[key] = value;
    } else if (value && typeof value === "object" && !Array.isArray(value)) {
      out[key] = mergeConfig(out[key] ?? {}, value);
    } else {
      out[key] = value;
    }
  }
  return out;
}

function routesFromEnv(name) {
  return String(process.env[name] || "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
    .map((path) => ({ path }));
}
