export const SOURCES = [
  {
    id: "openai-news",
    name: "OpenAI News",
    feedUrl: "https://openai.com/news/rss.xml",
    homepage: "https://openai.com/news/",
    section: "models",
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    feedUrl: "https://www.anthropic.com/news/rss.xml",
    homepage: "https://www.anthropic.com/news",
    section: "models",
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    homepage: "https://huggingface.co/blog",
    section: "tools",
  },
  {
    id: "github-changelog",
    name: "GitHub Changelog",
    feedUrl: "https://github.blog/changelog/feed/",
    homepage: "https://github.blog/changelog/",
    section: "tools",
  },
  {
    id: "arxiv-ai",
    name: "arXiv cs.AI",
    feedUrl: "https://rss.arxiv.org/rss/cs.AI",
    homepage: "https://arxiv.org/list/cs.AI/recent",
    section: "research",
  },
];

export const DEFAULT_KEYWORDS = [
  "agent",
  "agents",
  "ai",
  "api",
  "benchmark",
  "code",
  "coding",
  "context",
  "developer",
  "evaluation",
  "eval",
  "inference",
  "llm",
  "mcp",
  "model",
  "multimodal",
  "reasoning",
  "tool",
  "workflow",
  "智能体",
  "模型",
  "推理",
  "评测",
  "工具",
  "开发者",
];
